name: android_push_notification_icons
description: A package which simplifies the task of updating your android push notification icons.
version: 0.1.0
maintainer: Konstantin Kinzel (@KonstantinKinzel)

dependencies:
  args: ^2.4.0
  image: ^4.0.0
  path: ^1.8.2
  yaml: ^3.1.1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.17.11
